using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Logic.Enums
{
    public enum Country
    {
        Afghanistan,
        Argentina,
        Australia,
        Bahrain,
        Bangladesh,
        Belgium,
        Bosnia_and_Herzegovina,
        Brazil,
        Bulgaria,
        Canada,
        Chile,
        China,
        Colombia,
        Croatia,
        Cyprus,
        Denmark,
        Egypt,
        Eritrea,
        Ethiopia,
        Finland,
        France,
        Georgia,
        Germany,
        Ghana,
        Greece,
        Hungary,
        India,
        Indonesia,
        Iran,
        Iraq,
        Italy,
        Japan,
        Jordan,
        Kuwait,
        Lebanon,
        Libya,
        Luxembourg,
        Malaysia,
        Maldives,
        Mexico,
        Monaco,
        Morocco,
        Netherlands,
        Niger,
        Oman,
        Pakistan,
        Poland,
        Portugal,
        Qatar,
        Romania,
        Saudi_Arabia,
        Somalia,
        Sudan,
        Switzerland,
        Syria,
        Thailand,
        Tunisia,
        Ukraine,
        Vietnam,
        Yemen
    }
}
